version: '3'
services:
  postgres_historical:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - postgres_historical_data:/var/lib/postgresql/data
    environment:
      - POSGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8001:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 3s
      timeout: 60s
      retries: 10
      start_period: 30s
  postgres_main:
    image: postgres:14-alpine
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    environment:
      - POSGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8002:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 3s
      timeout: 60s
      retries: 10
      start_period: 30s
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq/mnesia/'
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 10s
      timeout: 60s
      retries: 10
      start_period: 30s
volumes:
  rabbitmq_data:
    driver: local
  postgres_historical_data:
    driver: local
  postgres_main_data:
    driver: local
    
    